### ISSUE TITLE
Converting Eudex to JavaScript

### ISSUE THREAD

**Issue by exebook** [ticki/eudex#11]
I am having a hard time trying to convert Eudex to JavaScript, because there is no such thing as 64 bit integer. You can sort of "emulate" it with two numbers, which I am currently trying to do, but I am just curious, why 64 bit? Can this be adapted to 32 bit? In hash tables you normally do not need this huge amount of bits anyway.

**Comment by ticki** [comment]
Well, you would loose precisions, but yeah, it is possible.

**Comment by Yomguithereal** [comment]
Hello @exebook & @ticki. I've just completed an implementation of Eudex for JavaScript for the [Talisman](https://github.com/Yomguithereal/talisman) library ([hashing](https://github.com/Yomguithereal/talisman/blob/master/src/phonetics/eudex.js), [distance](https://github.com/Yomguithereal/talisman/blob/master/src/metrics/distance/eudex.js)), with support for 64bit integers. Still, I guess a reduced version to 32 bit or some trick to fit in smaller sizes would be way more performant for JavaScript.

Have a good day :)

**Comment by ticki** [comment]
@Yomguithereal Thanks a lot, I've added it to the readme.

**Comment by ticki** [comment]
I'll close this for now.

**Comment by Yomguithereal** [comment]
@ticki, I added documentation in the library for the JavaScript ported functions [here](http://yomguithereal.github.io/talisman/phonetics/#eudex). Can you tell me whether I got it right and whether I messed something up please?

**Comment by ticki** [comment]
@Yomguithereal Looks very good! I don't know the details of Javascript, but, as far as I can tell, the implementation is correct.
