### ISSUE TITLE
 let mut n = 1u8;

### ISSUE THREAD

**Issue by exebook** [ticki/eudex#12]
`line 250     let mut n = 1u8;`
Are you sure this must be u8? Because I suspect it prevents words longer than 16 characters to hash properly.

**Comment by exebook** [comment]
I got my JavaScript port get same results as your implementation, but only for shorter strings. This one already gets different: `helloworldofeudex`

Rust version: a200a11800440018

JS version: a318004400180084

This is just because it runs few iterations more.

Did I miss somewhere in the README that we are limited by 16 chars?

**Comment by ticki** [comment]
Actually, it has this limit (sorry, the readme should mention it), but it doesn't affect the results much, due to the first letters dictating most of the sound.
