### ISSUE TITLE
comparing to b'z'

### ISSUE THREAD

**Issue by exebook** [ticki/eudex#13]
`if entry <= b'z' {`

I am new to Rust so I may get it wrong, but it feels like you are comparing against ordinal('z'), is this the right thing to do? Because you already `entry = (string[b] | 32).wrapping_sub(b'a')`

I do not know what `wrapping_sub` does, I refer to Java port, so it feels you need to compare to 26 instead.

**Comment by ticki** [comment]
Good catch.
