### ISSUE TITLE
Consider newtyping the hash return type

### ISSUE THREAD

**Issue by flo-l** [ticki/eudex#7]
As there has been [confusion on reddit](https://www.reddit.com/r/rust/comments/4ibk4a/eudex_10_is_ready_unicode_support_better_phone/d2wynvr) regarding the interpretation of the hash value it might be a good idea to newtype the u64 the hasher returns right now.

The newtype could have methods like `distance()` and `weighted_distance()` (or however you'd like to call them) and of course a `From`/`Into` impl for conversions to u64.

_Edit:_ and of course `similar()`

**Comment by ticki** [comment]
Great idea.

**Comment by flo-l** [comment]
I could write the code if you want to, but I haven't got enough time today. Tomorrow should be possible though. It's not that much work I guess..

**Comment by ticki** [comment]
Don't worry, I am already at it.

**Comment by flo-l** [comment]
great :joy:

**Comment by ticki** [comment]
This is done now.

**Comment by flo-l** [comment]
looks great!!
