### ISSUE TITLE
Java port info

### ISSUE THREAD

**Issue by jprante** [ticki/eudex#8]
FWIW I ported Eudex to Java at https://github.com/jprante/elasticsearch-analysis-phonetic-eudex/blob/master/src/main/java/org/xbib/elasticsearch/index/analysis/phonetic/Eudex.java with tests at https://github.com/jprante/elasticsearch-analysis-phonetic-eudex/blob/master/src/test/java/org/xbib/elasticsearch/index/analysis/phonetic/EudexTests.java and wrapped an Elasticsearch analysis plugin around it for experimenting.

**Comment by ticki** [comment]
That's pretty cool!

**Comment by ticki** [comment]
I have added it to the readme.
